add terraform configuration

diff --git a/.github/workflows/backend-cd.yml b/.github/workflows/backend-cd.yml
--- a/.github/workflows/backend-cd.yml
+++ b/.github/workflows/backend-cd.yml
@@ -1,4 +1,4 @@
-name: CD - Deploy Backend Services to AKS
+name: Backend CD - Deploy Backend Services to AKS
 
 on:
   workflow_run:
@@ -11,44 +11,174 @@ on:
       aks_cluster_name:
         description: 'Name of the AKS Cluster to deploy to'
         required: false
-        default: 'week09-aks'
+        default: 'chriswen430-aks'
       aks_resource_group:
         description: 'Resource Group of the AKS Cluster'
         required: false
-        default: 'deakinuni'
+        default: 'chriswen430-rg'
       aks_acr_name:
         description: 'Name of ACR'
         required: false
-        default: 'chriswen430week09acr'
+        default: 'chriswen430acr'
   workflow_call:
     inputs:
       aks_cluster_name:
         required: false
         type: string
-        default: 'week09-aks'
+        default: 'chriswen430-aks'
       aks_resource_group:
         required: false
         type: string
-        default: 'deakinuni'
+        default: 'chriswen430-rg'
       aks_acr_name:
         required: false
         type: string
-        default: 'chriswen430week09acr'
-
+        default: 'chriswen430acr'
 
 jobs:
+  staging_test_and_deploy:
+    runs-on: ubuntu-latest
+    outputs:
+      CUSTOMER_API_IP: ${{ steps.get_customer_ip.outputs.external_ip }}
+      PRODUCT_API_IP: ${{ steps.get_product_ip.outputs.external_ip }}
+      ORDER_API_IP: ${{ steps.get_order_ip.outputs.external_ip }}
+
+    steps:
+      # 1. Checkout the repository code
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      
+      # 2. Azure Login using Service Principal
+      - name: Log in to Azure
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+          enable-AzPSSession: true
+
+      # 3. Terraform Init and Apply to provision AKS, ACR, Networking, etc.
+      - name: Terraform Init (Staging Environment)
+        uses: hashicorp/terraform-github-actions@v1.4.0
+        with:
+          tf_actions_version: latest
+          tf_actions_subcommand: 'init'
+          tf_actions_working_directory: 'terraform'
+          
+      # 4. Terraform Apply to provision AKS, ACR, Networking, etc.
+      - name: Terraform Apply (Provision Staging Environment)
+        uses: hashicorp/terraform-github-actions@v1.4.0
+        with:
+          tf_actions_version: latest
+          tf_actions_subcommand: 'apply'
+          tf_actions_working_directory: 'terraform'
+          tf_actions_auto_approve: true
+          tf_actions_backend_type: 'azurerm'
+      
+      # 5. Deploy backend Infrastructure to the staging AKS cluster
+      - name: Deploy Backend Infrastructure to Staging AKS
+        run: |
+          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}
+          kubectl apply -f k8s/configmaps.yaml
+          kubectl apply -f k8s/secrets.yaml
+          kubectl apply -f k8s/customer-db.yaml
+          kubectl apply -f k8s/order-db.yaml
+          kubectl apply -f k8s/product-db.yaml
+
+      # 6. Deploy backend microservices to the staging AKS cluster
+      - name: Deploy Backend Microservices to Staging AKS
+        run: |
+          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}
+          kubectl apply -f k8s/customer-service.yaml
+          kubectl apply -f k8s/product-service.yaml
+          kubectl apply -f k8s/order-service.yaml
+
+      # 7. Wait for LoadBalancer IPs to be assigned
+      - name: Wait for Backend LoadBalancer IPs in Staging
+        run: |
+          echo "Waiting for Product, Order LoadBalancer IPs to be assigned (up to 5 minutes)..."
+          PRODUCT_IP=""
+          CUSTOMER_IP=""
+          ORDER_IP=""
+          
+          for i in $(seq 1 60); do
+            echo "Attempt $i/60 to get IPs..."
+            CUSTOMER_IP=$(kubectl get service customer-service-task10-2d -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            PRODUCT_IP=$(kubectl get service product-service-task10-2d -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            ORDER_IP=$(kubectl get service order-service-task10-2d -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+
+            if [[ -n "$CUSTOMER_IP" &&  -n "$PRODUCT_IP" && -n "$ORDER_IP" ]]; then
+              echo "All backend LoadBalancer IPs assigned!"
+              echo "Customer Service IP: $CUSTOMER_IP"
+              echo "Product Service IP: $PRODUCT_IP"
+              echo "Order Service IP: $ORDER_IP"
+              break
+            fi
+            sleep 5 # Wait 5 seconds before next attempt
+          done
+          
+          if [[ -z "$CUSTOMER_IP" || -z "$PRODUCT_IP" || -z "$ORDER_IP" ]]; then
+            echo "Error: One or more LoadBalancer IPs not assigned after timeout."
+            exit 1 # Fail the job if IPs are not obtained
+          fi
+          
+          # These are environment variables for subsequent steps in the *same job*
+          # And used to set the job outputs
+          echo "CUSTOMER_IP=$CUSTOMER_IP" >> $GITHUB_ENV
+          echo "PRODUCT_IP=$PRODUCT_IP" >> $GITHUB_ENV
+          echo "ORDER_IP=$ORDER_IP" >> $GITHUB_ENV
+  
+      # 8. Capture Customer Service IP for Workflow Output
+      - name: Run Simple Acceptance Tests
+        run: |
+          echo "Running simple acceptance tests against deployed services..."
+          if curl -s --head http://${{ env.CUSTOMER_IP }}:8002/health | grep "200 OK" > /dev/null; then
+            echo "Customer Service is healthy."
+          else
+            echo "Customer Service health check failed."
+            exit 1
+          fi
+          
+          if curl -s --head http://${{ env.PRODUCT_IP }}:8000/health | grep "200 OK" > /dev/null; then
+            echo "Product Service is healthy."
+          else
+            echo "Product Service health check failed."
+            exit 1
+          fi
+
+          if curl -s --head http://${{ env.ORDER_IP }}:8001/health | grep "200 OK" > /dev/null; then
+            echo "Order Service is healthy."
+          else
+            echo "Order Service health check failed."
+            exit 1
+          fi
+          echo "All acceptance tests passed."
+
+      # 9. Capture Customer Service IP for Workflow Output
+      - name: Terraform Destroy (Clean Up Staging Environment)
+        if: always()
+        uses: hashicorp/terraform-github-actions@v1.4.0
+        with:
+          tf_actions_version: latest
+          tf_actions_subcommand: 'destroy'
+          tf_actions_working_directory: 'terraform'
+          tf_actions_auto_approve: true
+          tf_actions_backend_type: 'azurerm'
+
+
   deploy_backend:
     runs-on: ubuntu-latest
     environment: Production
     
     outputs:
+      CUSTOMER_API_IP: ${{ steps.get_customer_ip.outputs.external_ip }}
       PRODUCT_API_IP: ${{ steps.get_product_ip.outputs.external_ip }}
       ORDER_API_IP: ${{ steps.get_order_ip.outputs.external_ip }}
 
     steps:
+      # 1. Checkout the repository code
       - name: Checkout repository
         uses: actions/checkout@v4
-
+      
+      # 2. Azure Login using Service Principal
       - name: Log in to Azure
         uses: azure/login@v1
         with:
@@ -57,29 +187,34 @@ jobs:
 
       - name: Set Kubernetes context (get AKS credentials)
         run: |
-          AKS_CLUSTER_NAME=${{ github.event.inputs.aks_cluster_name || 'week09-aks' }}
-          AKS_RESOURCE_GROUP=${{ github.event.inputs.aks_resource_group || 'deakinuni' }}
+          AKS_CLUSTER_NAME=${{ github.event.inputs.aks_cluster_name || 'chriswen430-aks' }}
+          AKS_RESOURCE_GROUP=${{ github.event.inputs.aks_resource_group || 'chriswen430-rg' }}
           az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
 
       - name: Get latest Docker image versions from ACR
         id: get_latest_versions
         run: |
-          AKS_ACR_NAME=${{ github.event.inputs.aks_acr_name || 'chriswen430week09acr' }}
+          AKS_ACR_NAME=${{ github.event.inputs.aks_acr_name || 'chriswen430acr' }}
+          CUSTOMER_TAG=$(az acr repository show-tags --name $AKS_ACR_NAME --repository customer_service --query "sort(@)[-1]" -o tsv)
           PRODUCT_TAG=$(az acr repository show-tags --name $AKS_ACR_NAME --repository product_service --query "sort(@)[-1]" -o tsv)
           ORDER_TAG=$(az acr repository show-tags --name $AKS_ACR_NAME --repository order_service --query "sort(@)[-1]" -o tsv)
 
+          if [[ -z "$CUSTOMER_TAG" ]]; then CUSTOMER_TAG=latest; fi
           if [[ -z "$PRODUCT_TAG" ]]; then PRODUCT_TAG=latest; fi
           if [[ -z "$ORDER_TAG" ]]; then ORDER_TAG=latest; fi
 
+          echo "CUSTOMER_TAG=$CUSTOMER_TAG" >> $GITHUB_ENV
           echo "PRODUCT_TAG=$PRODUCT_TAG" >> $GITHUB_ENV
           echo "ORDER_TAG=$ORDER_TAG" >> $GITHUB_ENV
+          echo "Latest Customer Service image: $CUSTOMER_TAG"
           echo "Latest Product Service image: $PRODUCT_TAG"
           echo "Latest Order Service image: $ORDER_TAG"
   
       # modify k8s yaml files to use the latest image versions
       - name: Update Kubernetes YAML with latest image versions
         run: |
-          AKS_ACR_NAME=${{ github.event.inputs.aks_acr_name || 'chriswen430week09acr' }}
+          AKS_ACR_NAME=${{ github.event.inputs.aks_acr_name || 'chriswen430acr' }}
+          sed -i "s|image: .*customer_service:.*|image: $AKS_ACR_NAME.azurecr.io/customer_service:${CUSTOMER_TAG}|g" k8s/customer-service.yaml
           sed -i "s|image: .*product_service:.*|image: $AKS_ACR_NAME.azurecr.io/product_service:${PRODUCT_TAG}|g" k8s/product-service.yaml
           sed -i "s|image: .*order_service:.*|image: $AKS_ACR_NAME.azurecr.io/order_service:${ORDER_TAG}|g" k8s/order-service.yaml
 
@@ -89,6 +224,7 @@ jobs:
           cd k8s/
           kubectl apply -f configmaps.yaml
           kubectl apply -f secrets.yaml
+          kubectl apply -f customer-db.yaml
           kubectl apply -f product-db.yaml
           kubectl apply -f order-db.yaml
 
@@ -96,12 +232,14 @@ jobs:
         run: |
           echo "Deploying backend microservices..."
           cd k8s/
+          kubectl apply -f customer-service.yaml
           kubectl apply -f product-service.yaml
           kubectl apply -f order-service.yaml
       
       - name: Wait for Backend LoadBalancer IPs
         run: |
           echo "Waiting for Product, Order LoadBalancer IPs to be assigned (up to 5 minutes)..."
+          CUSTOMER_IP=""
           PRODUCT_IP=""
           ORDER_IP=""
           
@@ -110,8 +248,9 @@ jobs:
             PRODUCT_IP=$(kubectl get service product-service-w08e1 -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
             ORDER_IP=$(kubectl get service order-service-task10-2d -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
 
-            if [[ -n "$PRODUCT_IP" && -n "$ORDER_IP" ]]; then
+            if [[ -n "$CUSTOMER_IP" && -n "$PRODUCT_IP" && -n "$ORDER_IP" ]]; then
               echo "All backend LoadBalancer IPs assigned!"
+              echo "Customer Service IP: $CUSTOMER_IP"
               echo "Product Service IP: $PRODUCT_IP"
               echo "Order Service IP: $ORDER_IP"
               break
@@ -119,15 +258,20 @@ jobs:
             sleep 5 # Wait 5 seconds before next attempt
           done
           
-          if [[ -z "$PRODUCT_IP" || -z "$ORDER_IP" ]]; then
+          if [[ -z "$CUSTOMER_IP" || -z "$PRODUCT_IP" || -z "$ORDER_IP" ]]; then
             echo "Error: One or more LoadBalancer IPs not assigned after timeout."
             exit 1 # Fail the job if IPs are not obtained
           fi
           
           # These are environment variables for subsequent steps in the *same job*
           # And used to set the job outputs
+          echo "CUSTOMER_IP=$CUSTOMER_IP" >> $GITHUB_ENV
           echo "PRODUCT_IP=$PRODUCT_IP" >> $GITHUB_ENV
           echo "ORDER_IP=$ORDER_IP" >> $GITHUB_ENV
+      
+      - name: Capture Customer Service IP for Workflow Output
+        id: get_customer_ip
+        run: echo "external_ip=${{ env.CUSTOMER_IP }}" >> $GITHUB_OUTPUT
 
       - name: Capture Product Service IP for Workflow Output
         id: get_product_ip
diff --git a/.github/workflows/backend-ci.yml b/.github/workflows/backend-ci.yml
--- a/.github/workflows/backend-ci.yml
+++ b/.github/workflows/backend-ci.yml
@@ -12,7 +12,7 @@ on:
   push:
     branches:
       - main
-      - test
+      - testing
     paths: # Only trigger if changes are in backend directories
       - 'backend/**'
       - '.github/workflows/backend_ci.yml' # Trigger if this workflow file changes
@@ -22,7 +22,7 @@ on:
 env:
   # ACR Login Server (e.g., myregistry.azurecr.io)
   # This needs to be set as a GitHub Repository Secret
-  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
+  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
   # Dynamically generate image tags based on Git SHA and GitHub Run ID
   # This provides unique, traceable tags for each image build
   # IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
@@ -34,6 +34,36 @@ jobs:
     runs-on: ubuntu-latest # Use a GitHub-hosted runner
 
     services:
+      # Customer DB
+      customer_db:
+        image: postgres:15
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: customers
+        ports:
+          - 5431:5432
+        options: >-
+          --health-cmd "pg_isready -U postgres"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+
+      # Order DB
+      order_db:
+        image: postgres:15
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: orders
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd "pg_isready -U postgres"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+
       # Product DB container
       product_db:
         image: postgres:15
@@ -48,35 +78,28 @@ jobs:
           --health-timeout 5s
           --health-retries 5
         ports:
-          - 5432:5432
-      
-      # Order DB
-      order_db:
-        image: postgres:15
-        env:
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: orders
-        ports:
           - 5433:5432
-        options: >-
-          --health-cmd "pg_isready -U postgres"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-
+      
+      
     steps:
       # 1. Checkout the repository code to the runner
       - name: Checkout repository
         uses: actions/checkout@v4 # Action to check out your repository code
 
-      # 2. Set up Python environment
+      # 2. Statistic code analysis
+      - name: Code Quality Checks
+        run: |
+          pip install flake8 bandit
+          flake8 backend/order_service
+          bandit -r backend/order_service
+    
+      # 3. Set up Python environment
       - name: Set up Python 3.10
         uses: actions/setup-python@v5 # Action to set up Python environment
         with:
           python-version: '3.10'
 
-      # 3. Install dependencies and run code quality checks
+      # 4. Install dependencies and run code quality checks
       - name: Install dependencies
         run: | # Use a multi-line script to install pip dependencies
           pip install --upgrade pip
@@ -88,25 +111,47 @@ jobs:
           # Install CI tools
           pip install pytest httpx
 
-      # 4. Run tests for product service
-      - name: Run product_service tests
-        working-directory: backend/product_service
+      # 5. Wait for Postgres services to be healthy
+      - name: Wait for Postgres to be ready
+        run: |
+          for port in 5431 5432 5433; do
+            until pg_isready -h localhost -p $port -U postgres; do
+              echo "Waiting for postgres on port $port..."
+              sleep 2
+            done
+          done
+
+      # 6. Run tests for customer service
+      - name: Run customer_service tests
+        working-directory: backend/customer_service
         env:
           POSTGRES_HOST: localhost
-          POSTGRES_PORT: 5432
-          POSTGRES_DB: products
+          POSTGRES_PORT: 5431
+          POSTGRES_DB: customers
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
         run: |
           pytest tests --maxfail=1 --disable-warnings -q
-      
-      # 5. Run tests for order service
+
+      # 7. Run tests for order service
       - name: Run order_service tests
         working-directory: backend/order_service
         env:
           POSTGRES_HOST: localhost
-          POSTGRES_PORT: 5433
+          POSTGRES_PORT: 5432
           POSTGRES_DB: orders
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+        run: |
+          pytest tests --maxfail=1 --disable-warnings -q
+
+      # 8. Run tests for product service
+      - name: Run product_service tests
+        working-directory: backend/product_service
+        env:
+          POSTGRES_HOST: localhost
+          POSTGRES_PORT: 5433
+          POSTGRES_DB: products
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
         run: |
@@ -116,19 +161,19 @@ jobs:
   build_and_push_images:
     runs-on: ubuntu-latest
     needs: test_and_lint_backends
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 
     steps:
+    # 1. Checkout the repository code to the runner
     - name: Checkout repository
       uses: actions/checkout@v4
 
-    # Azure login using a Service Principal secret
+    # 2. Azure login using a Service Principal secret
     - name: Azure Login
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }} # Needs to be set as a GitHub Secret (Service Principal JSON)
 
-    # Login to Azure Container Registry (ACR)
+    # 3. Login to Azure Container Registry (ACR)
     - name: Login to Azure Container Registry
       run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}
     
@@ -136,6 +181,15 @@ jobs:
     - name: Determine next image version
       id: version
       run: |
+        # customer service
+        if az acr repository show --name ${{ env.ACR_LOGIN_SERVER }} --repository customer_service >/dev/null 2>&1; then
+          latest_customer=$(az acr repository show-tags --name ${{ env.ACR_LOGIN_SERVER }} --repository customer_service --query "sort(@)[-1]" -o tsv)
+          latest_customer_version=$(( ${latest_customer#v} + 1 ))
+        else
+          latest_customer_version=1
+        fi
+        echo "CUSTOMER_VERSION=v$latest_customer_version" >> $GITHUB_ENV
+
         # Product service
         if az acr repository show --name ${{ env.ACR_LOGIN_SERVER }} --repository product_service >/dev/null 2>&1; then
           latest=$(az acr repository show-tags --name ${{ env.ACR_LOGIN_SERVER }} --repository product_service --query "sort(@)[-1]" -o tsv)
@@ -154,19 +208,48 @@ jobs:
         fi
         echo "ORDER_VERSION=v$latest_order_version" >> $GITHUB_ENV
 
-    # Build and Push Docker image for Product Service
+  
+    # 5. Build and Push Docker image for Customer Service
+    - name: Build and Push Customer Service Image
+      run: |
+        docker build -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.CUSTOMER_VERSION }} ./backend/customer_service/
+        docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.CUSTOMER_VERSION }}
+
+    # 6. Build and Push Docker image for Product Service
     - name: Build and Push Product Service Image
       run: |
         docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.PRODUCT_VERSION }} ./backend/product_service/
         docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.PRODUCT_VERSION }}
 
-    # Build and Push Docker image for Order Service
+    # 7. Build and Push Docker image for Order Service
     - name: Build and Push Order Service Image
       run: |
         docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.ORDER_VERSION }} ./backend/order_service/
         docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.ORDER_VERSION }}
 
-    # Logout from Azure for security (runs even if image push fails)
+    # 8. Run Docker Scout to analyze images for vulnerabilities
+    - name: Docker Scout Analysis
+      run: |
+        set -e
+        echo "Scanning Customer Service..."
+        docker scout cves ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.CUSTOMER_VERSION }} > customer_report.txt
+        
+        echo "Scanning Product Service..."
+        docker scout cves ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.PRODUCT_VERSION }} > product_report.txt
+        
+        echo "Scanning Order Service..."
+        docker scout cves ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.ORDER_VERSION }} > order_report.txt
+        
+        # Combine reports
+        echo "==== Customer Service ====" > full_report.txt
+        cat customer_report.txt >> full_report.txt
+        echo "==== Product Service ====" >> full_report.txt
+        cat product_report.txt >> full_report.txt
+        echo "==== Order Service ====" >> full_report.txt
+        cat order_report.txt >> full_report.txt
+        cat full_report.txt
+
+    # 9. Logout from Azure for security (runs even if image push fails)
     - name: Logout from Azure
       run: az logout
       if: always()
